name: PortalHelper
main: com.github.joelgodofwar.ph.Main
version: 1.0.4
author: JoelGodOfWar

commands:
  portalhelper:
    aliases: ph
    description: Shows PortalHelper help.
    usage: /<command>

permissions:
  portalhelper.config:
    description: Allows player to change configs.
    default: false